services:
  daemon:
    build: .
    image: agin-sensors-daemon
    container_name: agin-sensors-daemon
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "${DAEMON_PORT_3000:-3000}:3000"
      - "${DAEMON_PORT_3001:-3001}:3001"
    volumes:
      - ./${CONFIG_FOLDER_PATH:-config}:/app/config:ro
      - ./.env:/app/.env:ro
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - CONFIG_FOLDER_PATH=/app/config
    networks:
      - agin-sensors

  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=7woUG5snFpSNbwr7
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_BUCKET=test-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=7kvQLYnWRXZo2xkmfYi14_OSD3kOk93rwZ0SsdTMsttaw33AMaaGCgg6Bf_-yvEgE3736byabQFFZEA1CXwXFg==
    ports:
      - "8086:8086"
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
    networks:
      - agin-sensors

  timescaledb-ha:
    container_name: timescaledb
    ports:
      - 5432:5432
    volumes:
      - ./timescale/postgresql.conf:/pgdata/postgresql.conf
      - ./timescale/data:/pgdata
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=password
    image: timescale/timescaledb-ha:pg17
    networks:
      - agin-sensors

networks:
  agin-sensors:
    driver: bridge
