services:
  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=7woUG5snFpSNbwr7
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_BUCKET=test-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=7kvQLYnWRXZo2xkmfYi14_OSD3kOk93rwZ0SsdTMsttaw33AMaaGCgg6Bf_-yvEgE3736byabQFFZEA1CXwXFg==
    ports:
      - "8086:8086"
    volumes:
      - ./influx/data:/var/lib/influxdb2
      - ./influx/config:/etc/influxdb2
  timescaledb-ha:
    container_name: timescaledb
    ports:
      - 5432:5432
    volumes:
      - ./timescale/postgresql.conf:/pgdata/postgresql.conf
      - ./timescale/data:/pgdata
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=password
    image: timescale/timescaledb-ha:pg17
  agin-sensors:
    image: ghcr.io/aginrocks/agin-sensors:latest
    restart: unless-stopped
    build: .

