# yaml-language-server: $schema=https://github.com/aginrocks/agin-sensors/raw/refs/heads/main/daemon/global_schema.json
databases:
  influx:
    type: influxdb
    url: http://localhost:8086
    token: 7kvQLYnWRXZo2xkmfYi14_OSD3kOk93rwZ0SsdTMsttaw33AMaaGCgg6Bf_-yvEgE3736byabQFFZEA1CXwXFg==
    organization: test-org
connectors:
  socketio:
    type: socketio
    port: 3000
  socketio1:
    type: socketio
    port: 3001
  mqtt:
    type: mqtt
    host: localhost
    port: 1883
    format: beanair
