# yaml-language-server: $schema=../organizations_schema.json

org1:
  name: Organization One
  buffer: true
  modifiers:
    - ModifierTemplate
  filters:
    - type: macs
      macs:
        - 66:77:88:99:AA:BB
    - type: tokens
      tokens:
        - token1
        - token2
  databases:
    - key: influx
      type: influxdb
      bucket: org1_bucket
    - key: influx
      type: influxdb
      bucket: test-bucket
org2:
  name: Organization Two
  filters:
    - type: macs
      macs:
        - mac69
        - 00:11:22:33:44:55
        - 66:77:88:99:AA:BB
    - type: tokens
      tokens:
        - token1
        - token2
  databases:
    - key: influx
      type: influxdb
      bucket: org2_bucket
